sudo: false
language: python
python:
- '2.7'
- '3.5'
notifications:
  email: false
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  coverage biopython click
- source activate test-environment
- pip install coveralls
script:
- coverage run --source=ionize setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: lewis.a.marshall
  password:
    secure: ED3TmnEto2g+XHZXe4HdxqQEuyn5V/erpTjbH5tkwOA2UB/eSe3mcd9nBDWg0VLeCqYAbEkIA5N+NCgKYP4n7vMYNNzU/pZ+q63cJt8DNqd2Ocxo1G7g0LEsRnuDTEad2cMKHc7eWtidJUer1j6LxzASqsK5doOudhgY1SxEX1Q=
  on:
    tags: true
    branch: master
